title: Neuro Schedule
description: Just a personal project of mine to get a Schedule for Neuro/Evil/Vedal streams onto my phone Calendar without manually adding it each time...
theme: jekyll-theme-hacker
